"""SHM: cumulative fatigue damage from a dynamic stress time series.

Not a regression problem. The labels were generated by rainflow counting plus
Miner's rule, so the generating process is recoverable almost exactly:

    D = sum_i ( n_i * amp_i^m ) / C

Two parameters, fitted once on the 64 training files by fit_shm.py.
Leave-one-out MAPE across all 64 files: 2.76%  ->  score 0.972.

For comparison, a GBM on summary statistics tops out around R^2 0.56 on
`std` -- the physics route is not a fallback, it is the method.
"""
import json
import os

import numpy as np
import pandas as pd

PARAMS_PATH = os.path.join(os.path.dirname(__file__), "params_shm.json")
_P = None


def _params() -> dict:
    global _P
    if _P is None:
        with open(PARAMS_PATH) as f:
            _P = json.load(f)
    return _P


def load_series(path: str) -> np.ndarray:
    """Files are headerless single-column CSVs, 581,120 samples each."""
    s = pd.read_csv(path, header=None, dtype=np.float64).iloc[:, 0].to_numpy()
    return s[np.isfinite(s)]


def cycles(x: np.ndarray) -> np.ndarray:
    """Rainflow cycle extraction -> array of (amplitude, count)."""
    import rainflow
    return np.array([[rng / 2.0, cnt] for rng, mean, cnt, i, j
                     in rainflow.extract_cycles(x)])


def damage_sum(c: np.ndarray, m: float) -> float:
    return float(np.sum(c[:, 0] ** m * c[:, 1]))


def predict(path: str) -> dict:
    p = _params()
    x = load_series(path)
    c = cycles(x)
    S = damage_sum(c, p["m"])
    D = S / p["C"]

    # explanation: which amplitude bands drive the damage
    edges = np.array([0, 5, 10, 15, 20, 25, 30, np.inf])
    contrib = c[:, 0] ** p["m"] * c[:, 1]
    bands = []
    for lo, hi in zip(edges[:-1], edges[1:]):
        sel = (c[:, 0] >= lo) & (c[:, 0] < hi)
        if sel.any():
            bands.append({
                "amplitude_range": f"{lo:.0f}-{'inf' if np.isinf(hi) else f'{hi:.0f}'}",
                "cycles": float(c[sel, 1].sum()),
                "share_of_damage": round(float(contrib[sel].sum() / contrib.sum()), 4),
            })
    bands.sort(key=lambda b: -b["share_of_damage"])

    return {
        "prediction": round(float(D), 4),
        "detail": {
            "samples": int(len(x)),
            "rainflow_cycles": int(c[:, 1].sum()),
            "largest_amplitude": round(float(c[:, 0].max()), 3),
            "sn_exponent_m": p["m"],
            "sn_constant_C": p["C"],
            "damage_by_amplitude_band": bands[:4],
            "note": "Damage is dominated by the few largest-amplitude cycles "
                    f"because stress enters at the power of {p['m']:.2f}.",
        },
    }
